<?php
/**
 * @author     DCKAP
 * @package    DCKAP_Profiler
 * @copyright  Copyright (c) 2017 DCKAP Inc (http://www.dckap.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$mysqlprofiler = $block->getMysqlProfiler();
$block->downloadCSV();
$mysql_alert = $block->getConfigValue('profiler_section/profiler_group_general/mysql_alert');
?>
<table>
    <thead>
    <tr>
        <th>Total: <?php echo number_format($mysqlprofiler->getTotalElapsedSecs(), 2) ?> Secs</th>
        <th>Total Query: <?php echo $mysqlprofiler->getTotalNumQueries() ?></th>
        <th>Query Params</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($mysqlprofiler->getQueryProfiles() as $query): ?>
        <tr <?php if ($mysql_alert) {
            if ((trim(number_format($query->getElapsedSecs() * 1000, 2))) >= number_format($mysql_alert, 2)) {
                echo 'class = alert';
            }
        } ?>>
            <td><?php echo number_format(1000 * $query->getElapsedSecs(), 2) ?> ms</td>
            <td><?php echo $query->getQuery() ?></td>
            <td><?php echo json_encode($query->getQueryParams()) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>