<?php
/**
 * @author     DCKAP
 * @package    DCKAP_Profiler
 * @copyright  Copyright (c) 2017 DCKAP Inc (http://www.dckap.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

if (!$block->isEnabled()) {
    return;
}
?>
<div class="profiler_container">
    <h5>DCKAP Profiler</h5>
    <div class="total-server">
        <span>IP Address: <?php echo $_SERVER['REMOTE_ADDR'] ?></span>
        <span>Server Request Time: <?php echo round($block->getRequestTime(), 2) ?> Secs</span>
    </div>

    <ul class="container-titles">
        <li id="profiler" class="active">CODE Profiler</li>
        <li id="query" class="">MYSQL Profiler</li>
    </ul>

    <div id="container_profiler" class="page profile-table"><?php echo $block->getProfilerPage()->toHtml(); ?></div>
    <div id="container_query" class="page mysql-table"
         style="display: none;"><?php echo $block->getMysqlPage()->toHtml(); ?></div>
</div>
<script>
    require(['jquery'],
        function ($) {
            $('.container-titles li').on('click', function (e) {
                $('.container-titles li').removeClass("active");
                $('.page').hide();
                var id = $(e.currentTarget).attr('id');
                $(this).addClass("active");
                $('#container_' + id).show();
            });
        });
</script>

